"""add_tables

Revision ID: 8f453051a620
Revises:
Create Date: 2025-03-12 10:47:40.616731+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f453051a620"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employer_address", sa.String(), nullable=False),
        sa.Column("employee_address", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "WAITING_REVIEW",
                "COMPLETED",
                "CANCELLED",
                name="jobstatus",
            ),
            nullable=False,
            default="OPEN",
        ),
        sa.Column("payment", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("skills", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("applications", sa.ARRAY(sa.String()), default=[], nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("jobs_pkey")),
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("person_address", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("EMPLOYER", "EMPLOYEE", name="role"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("resumes_pkey")),
    )
    op.create_table(
        "ratings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("rated_person_address", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("EMPLOYER", "EMPLOYEE", name="role"), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("ratings_job_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ratings_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ratings")
    op.drop_table("resumes")
    op.drop_table("jobs")
    # ### end Alembic commands ###
